package com.revechelizarondo.battleship.features.common.theme.uicolors

import androidx.compose.ui.graphics.Color

object WildViolet : UIColor {
    override fun primaryLight() = Color(0xFF4E0078)
    override fun onPrimaryLight() = Color(0xFFFFFFFF)
    override fun primaryContainerLight() = Color(0xFF6A1B9A)
    override fun onPrimaryContainerLight() = Color(0xFFF2D6FF)
    override fun secondaryLight() = Color(0xFF462A58)
    override fun onSecondaryLight() = Color(0xFFFFFFFF)
    override fun secondaryContainerLight() = Color(0xFF806193)
    override fun onSecondaryContainerLight() = Color(0xFFFFFFFF)
    override fun tertiaryLight() = Color(0xFF62003E)
    override fun onTertiaryLight() = Color(0xFFFFFFFF)
    override fun tertiaryContainerLight() = Color(0xFF861058)
    override fun onTertiaryContainerLight() = Color(0xFFFFD4E4)
    override fun errorLight() = Color(0xFF740006)
    override fun onErrorLight() = Color(0xFFFFFFFF)
    override fun errorContainerLight() = Color(0xFFCF2C27)
    override fun onErrorContainerLight() = Color(0xFFFFFFFF)
    override fun backgroundLight() = Color(0xFFFFF7FC)
    override fun onBackgroundLight() = Color(0xFF1F1A21)
    override fun surfaceLight() = Color(0xFFFFF7FC)
    override fun onSurfaceLight() = Color(0xFF140F17)
    override fun surfaceVariantLight() = Color(0xFFEDDEEF)
    override fun onSurfaceVariantLight() = Color(0xFF3C3340)
    override fun surfaceTintLight() = primaryLight()

    override fun outlineLight() = Color(0xFF594F5D)
    override fun outlineVariantLight() = Color(0xFF746978)
    override fun scrimLight() = Color(0xFF000000)
    override fun inverseSurfaceLight() = Color(0xFF342E37)
    override fun inverseOnSurfaceLight() = Color(0xFFF9EDF9)
    override fun inversePrimaryLight() = Color(0xFFE4B5FF)
    override fun surfaceDimLight() = Color(0xFFCEC3CE)
    override fun surfaceBrightLight() = Color(0xFFFFF7FC)
    override fun surfaceContainerLowestLight() = Color(0xFFFFFFFF)
    override fun surfaceContainerLowLight() = Color(0xFFFBF0FB)
    override fun surfaceContainerLight() = Color(0xFFF0E5F0)
    override fun surfaceContainerHighLight() = Color(0xFFE4DAE5)
    override fun surfaceContainerHighestLight() = Color(0xFFD9CED9)

    override fun primaryDark() = Color(0xFFF1D1FF)
    override fun onPrimaryDark() = Color(0xFF3E0061)
    override fun primaryContainerDark() = Color(0xFFBB70EC)
    override fun onPrimaryContainerDark() = Color(0xFF000000)
    override fun secondaryDark() = Color(0xFFF1D1FF)
    override fun onSecondaryDark() = Color(0xFF351946)
    override fun secondaryContainerDark() = Color(0xFFA684B9)
    override fun onSecondaryContainerDark() = Color(0xFF000000)
    override fun tertiaryDark() = Color(0xFFFFD0E2)
    override fun onTertiaryDark() = Color(0xFF4F0031)
    override fun tertiaryContainerDark() = Color(0xFFE562A6)
    override fun onTertiaryContainerDark() = Color(0xFF000000)
    override fun errorDark() = Color(0xFFFFD2CC)
    override fun onErrorDark() = Color(0xFF540003)
    override fun errorContainerDark() = Color(0xFFFF5449)
    override fun onErrorContainerDark() = Color(0xFF000000)
    override fun backgroundDark() = Color(0xFF171219)
    override fun onBackgroundDark() = Color(0xFFEADFEA)
    override fun surfaceDark() = Color(0xFF171219)
    override fun onSurfaceDark() = Color(0xFFFFFFFF)
    override fun surfaceVariantDark() = Color(0xFF4D4351)
    override fun onSurfaceVariantDark() = Color(0xFFE6D8E9)
    override fun surfaceTintDark() = primaryDark()
    override fun outlineDark() = Color(0xFFBBAEBE)
    override fun outlineVariantDark() = Color(0xFF998C9C)
    override fun scrimDark() = Color(0xFF000000)
    override fun inverseSurfaceDark() = Color(0xFFEADFEA)
    override fun inverseOnSurfaceDark() = Color(0xFF2E2830)
    override fun inversePrimaryDark() = Color(0xFF6C1D9C)
    override fun surfaceDimDark() = Color(0xFF171219)
    override fun surfaceBrightDark() = Color(0xFF49424B)
    override fun surfaceContainerLowestDark() = Color(0xFF0A060C)
    override fun surfaceContainerLowDark() = Color(0xFF211C23)
    override fun surfaceContainerDark() = Color(0xFF2C262E)
    override fun surfaceContainerHighDark() = Color(0xFF373039)
    override fun surfaceContainerHighestDark() = Color(0xFF423B44)

}